function [fitresult, gof] = Spain_fit(time, spain)
%CREATEFIT(TIME,SPAIN)
%  Create a fit.
%
%  Data for 'Spain_Fit' fit:
%      X Input : time
%      Y Output: spain
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Mar-2020 18:53:48


%% Fit: 'Spain_Fit'.
[xData, yData] = prepareCurveData( time, spain );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Normalize = 'on';
opts.Robust = 'LAR';
opts.StartPoint = [8.45002969250837 5.17643710659505];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Spain_Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'spain vs. time', 'Spain_Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'time', 'Interpreter', 'none' );
ylabel( 'spain', 'Interpreter', 'none' );
grid on


